server:
  port: 0

spring:
  application:
    name: estampaider-backend
  datasource:
    url: jdbc:sqlite:estampaider.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
