server:
  port: 9091

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jaico98/config-repo-estampaider
          default-label: main
  application:
    name: config-server
